# Generated by Django 5.0.4 on 2024-04-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='vists',
            new_name='visits',
        ),
    ]
