# Generated by Django 5.0.3 on 2024-04-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('salary', models.FloatField()),
                ('joining_date', models.DateField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
